### PR TITLE
Feature/kickstart

### LINKED ISSUE #10: --kickstart option in metal boot
Whilst metal boot is running, render the template specified by a --kickstart option to metal boot as a temp file in /var/www/html/deployment/ks and update the ks= option in the pxeboot config files with that value. 

When the hunter process completes, as well as delete the pxeboot config file, also delete the rendered kickstart

If multiple nodes are specified with a genders group, create a kickstart file for each node and delete each one on completion.

### PR DESCRIPTION
**Pull request by WilliamMcCumstie**
Contains the kickstart feature that has also been integrated into boot.

Also has an updated version of Templater that supports recursive templates with arithmetic. Also fixed a file name error in hosts. Combined these two files are preventing the automerge

Fixes #10 #8 #7

### CODE REVIEW

**Comment by WilliamMcCumstie** [comment]
Resolved conflicts

**Comment by WilliamMcCumstie** [comment]
Need to fix:
Remove error when `metal kickstart` is ran
Change save file name each time `kickstart -g` is ran
Add a default file for `metal boot --kickstart`
Condense boot templates: compute.erb, login.erb, and infra.erb into install.erb
Allow the template's to be found by filename instead of full path

**Comment by WilliamMcCumstie** [comment]
Issues fixed

**Comment by ste78** [comment]
Can we also accept the template name without the .erb extension? ie -k compute

**Pull request merged**
