### PR TITLE
Deep merge template paramter hashes

### PR DESCRIPTION
**Pull request by WilliamMcCumstie**
Previously only the top level hash in the template parameter configs where being merged. Changes in sub-hashes would override the existing sub-hash in its entirety. Now a deep merge occurs where all sub-hashes are also merged.

Also fixed a bug in which only the top level keys where being converted to symbols.

### CODE REVIEW

**Comment by WilliamMcCumstie** [comment]
Also removed the last reference to `nodeattr` in `Templater`

**Comment by WilliamMcCumstie** [comment]
These changes LGTM

**Comment by BobWhitelock** [comment]
@WilliamMcCumstie: this LGTM, I've just made a few refactorings and  fixed how we handle nodes not in genders, can you take a quick look at the latest changes and merge them through if you're happy with them?

**Comment by WilliamMcCumstie** [comment]
LGTM, just updated an error message

**Pull request merged**
